import { Link } from "react-router-dom";
import GoogleBtn from './GoogleBtn';
import React, {useRef} from 'react';

//TODO:
//(DONE) COMPLETION METHOD -> CREATE TIMER
//(DONE) RENDER TEXT OF CURRENT ACTIVITY (RESTING OR WORKING)
//(DONE) CREATE USEEFFECT FOR SETTING LONG BREAK + SHORT BREAK + WORK ON TIME VARIABLE BASED ON POMODORO COUNT AND ACTIVITY STATES
//(DONE) SEND USER NOTIFICATIONS
//(DONE) START SOUND
//(DONE) SHORTEN IF STATEMENTS FOR COMPLETION
//(DONE) CREATE USESTATE FOR LONG KEY WORD AND ADD IT NEXT TO THE ACTIVITY
//(DONE) COUNTING COMPLETIONS
//(DONE) STOPPING === NO COUNTED COMPLETION
//(DONE) COMPLETION COUNTER AT TOP OF SCREEN
//(DONE) IMPORT REACT-ROUTER-DOM
//(DONE) CREATE LINKS, ROUTES, AND BROWSERROUTERS
//(DONE) STYLE LINKS INTO BUTTONS
//(DONE) CREATE SERVER FOR STATISTICS
//(DONE) MAKE AXIOS REQUEST
//(DONE) CREATE STATISTICS PAGE
//(DONE) ADD LIFETIME TOTAL AND DISPLAY ON TOP OF SCREEN
//(DONE) ADD POMODORO TOTALS FOR CURRENT HOUR AND TOTAL HOUR COUNT TO SERVER
//(DONE) REMOVE OLD DATA ONCE NEW DAY STARTS
//(DONE) ADD POMODORO TOTALS FOR CURRENT WEEK AND TOTAL WEEK COUNT TO SERVER
//(DONE) REMOVE OLD DATA ONCE NEW WEEK STARTS
//(DONE) ADD POMODORO TOTALS FOR CURRENT MONTH AND TOTAL MONTH COUNT TO SERVER
//(DONE) REMOVE OLD DATA ONCE NEW MONTH STARTS
//(DONE) ADD POMODORO TOTALS FOR CURRENT YEAR AND TOTAL YEAR COUNT TO SERVER
//(DONE) REMOVE OLD DATA ONCE NEW YEAR STARTS
//(DONE) CREATE PLACEHOLDER DAY GRAPH
//(DONE) STYLE NAVIGATION BUTTONS FOR STATS
//(DONE) MOVE ROUTES TO INDEX.JS
//(DONE) SET UP NAVIGATION WITH ROUTES + LINKS FOR EACH GRAPH
//(DONE) RESPONSIVE DESIGN GRAPHS
//(DONE) CREATE ALL PLACEHOLDER GRAPHS
//(DONE) CONNECT GRAPHS TO SERVER (DAY(DONE), WEEK(), MONTH(), YEAR())
//(DONE) CONNECT NECK AND EVERYTHING ELSE IN BLENDER TO CAT AND EXPORT AS FBX
//(DONE) CREATE BASIC ANIMATION IN UNITY
//(DONE) CREATE WEBGL BUILD
//(DONE) IMPORT REACT-UNITY-WEBGL AND SHOW CAT
//(DONE) ON CLICK, RUN ANIMATION
//(DONE) SET WORLD UNDERNEATH CAT
//(DONE) MOVE WEBGL APP INTO POMODORO APP
//(DONE) REMOVE ASYNC AND AWAIT
//(DONE) MOVE ELEMENTS ON TOP OF WEBGL
//(DONE) ADD FEEDING ANIMATION
//(DONE) SIZE CHANGES AFTER EACH POMODORO
//(DONE) SET PET SIZE ACCORDING TO POMODORO COUNT
//(DONE) CREATE NEW WORLD AND ASSETS
//(DONE) SHOW/HIDE OBJECTS
//(DONE) FIX PET SIZE AT FIRST LOAD ACCORDING TO POMODORO COUNT
//(DONE) CREATE CAMERA SLOW ZOOM OUT AND QUICK ZOOM ON UNITY LOAD
//(DONE) SLOW DOWN GROWTH
//(DONE) SCALE PET SIZE, CAMERA, AND CLOUD ACCORDINGLY
//(DONE) FIX GIT -> UPGRADE TO LARGE FILE SYSTEM
//(DONE) ADD SKYBOX
//(DONE) FIX SKYBOX POSITION
//(DONE) CHANGE 3D WORLDS ONCE POMODORO REACHES CERTAIN NUMBER
//(DONE) REMOVE COUNTER TEXT
//(DONE) CHECK IF SLOW PET SIZE INCREASE INSTEAD OF CLOUD ANIM LOOKS BETTER
//(DONE) FIX SHADOWS
//(DONE) COVER SCREEN WITH CLOUDS ONCE WORLD CHANGES
//(DONE) SET CHART TO BE RESPONSIVE ON MOUNT AND ON MANUAL SCREEN SIZE CHANGE
//(DONE) FIX SERVER(DONE), STATS.JS(DONE), AND TIMER.JS(DONE) SO DB STARTS AT 0
//(DONE) DISPLAY TOTALS ON STATS.JS PAGES
//(DONE) PERFECT RESPONSIVE TIMER (DONE), STATS (DONE), AND WEBGL (DONE)
//(DONE) CHANGE SKYBOX ON EARTH DISPLAY
//(DONE) SET COUNTDOWN TIMERS TO 25 and 5
//(DONE) DESIGN AND CREATE GOOGLE LOG IN BUTTON
//(DONE) ADD ALERT COVERING SCREEN
//(DONE) FIX RESPONSIVE ALERT
//(DONE) SLIDE NAV MENU FROM RIGHT
//(DONE) SHOW / HIDE GOOGLE LOGIN BUTTON
//() SET NAV ICONS
//(DONE) FIX GOOGLE BUTTON STYLING
//() RESPONSIVE NAV MENU
//() SHOW ALERT SCREEN ON UNITY LOAD AND WHEN USER IS NOT LOGGED IN 
//() REQUIRE LOG IN TO SHOW STATS
//() ASK USER TO LOG IN TO SHOW STATS
//() CHANGE DB AND SERVER CONNECTIONS FOR INDIVIDUAL GOOGLE ID'S
//() (OPTIONAL) ADD LEADERBOARDS FOR POMODORO COUNT
//() HOST REACT APP ON OWN WEBSITE => IF WEBGL DOESNT WORK, HOST ON GITHUB PAGES OR HEROKU
//() HOST JSON-SERVER ON HEROKU
//() SHOW LOADING ANIM OVER APP WHILE WAITING FOR HEROKU TO START

const App = () => {
	const nav = useRef(null);

	function showNav() {
		nav.current.style.right = "0px";
	}

	function hideNav() {
		nav.current.style.right = "-60%";
	}
	
	return (
		<div>
			<div class="mhead">
				<img className="menu-ham" src="/img/hamburger.png" onClick={showNav} />
			</div>
			<div className="menu" ref={nav}>
				<div className="close-menu">
					<img src="/img/exit.png" onClick={hideNav} className="menu-exit" />
				</div>
				<ul>
					<Link to="/">
						<li>Pomodoro</li>
					</Link>
					<Link to="/stats/day">
						<li>Statistics</li>
					</Link>
					<li>
						<GoogleBtn />
					</li>
				</ul>
			</div>
		</div>
	);
};

export default App;
